# https://prettier.io/docs/en/options.html

arrowParens: "always"
bracketSpacing: true
printWidth: 250
proseWrap: never
quoteProps: "as-needed"
semi: true
singleQuote: true
tabWidth: 4
trailingComma: "none"
useTabs: false